services:
  - type: web
    name: alpha-sp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alpha_sp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alpha_sp.settings
      - key: PYTHON_VERSION
        value: 3.10
